linters-settings:
  custom:
    logcheck:
      path: ./logcheck.so
      description: "Checks log messages for convention compliance"
      original-url: github.com/logcheck
      settings:
        config: ".logcheck.yml"

linters:
  enable:
    - logcheck
